server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location / {
        default_type text/plain;
        return 200 "packetbeat demo\n";
    }

    location /client-error {
        default_type text/plain;
        return 404 "not found\n";
    }

    location /server-error {
        default_type text/plain;
        return 500 "internal error\n";
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl_certificate     /etc/ssl/certs/packetbeat-demo.crt;
    ssl_certificate_key /etc/ssl/private/packetbeat-demo.key;

    location / {
        default_type text/plain;
        return 200 "packetbeat tls demo\n";
    }
}
