input {
  # NetFlow v5/v9 and IPFIX (default UDP 2055)
  udp {
    id => "netflow-v9-input"
    port => 2055
    workers => 4
    receive_buffer_bytes => 16777216

    codec => netflow {
      versions => [9]
    }

    tags => ["netflow"]
    type => "netflow"
  }
}

output {
  pipeline {
    send_to => ["main"]
  }
}
