"""Send incident summary emails via Kibana connector, SMTP, or local HTML fallback."""
from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import requests

from src.config import KBN_HEADERS, KIBANA_DIR, KIBANA_URL, ROOT


def render_email_html(report: dict) -> str:
    """Build customer-ready HTML from an RCA report dict."""
    timeline = report.get("timeline", [])
    evidence = report.get("evidence", [])
    remediation = report.get("remediation_actions", [])
    tl_rows = "".join(
        f"<tr><td style='padding:6px 10px;border-bottom:1px solid #eee;color:#666;'>{t['time']}</td>"
        f"<td style='padding:6px 10px;border-bottom:1px solid #eee;'>{t['event']}</td></tr>"
        for t in timeline
    )
    ev_items = "".join(f"<li style='margin-bottom:6px;'>{e}</li>" for e in evidence)
    rem_items = "".join(f"<li style='margin-bottom:6px;'>{r}</li>" for r in remediation)
    approval = report.get("approval", {})
    approval_line = (
        f"Approved by <strong>{approval.get('approved_by', 'auto')}</strong> "
        f"({approval.get('mode', 'manual')})"
        if report.get("remediated")
        else "Pending human approval"
    )
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{report.get('title', 'Incident Summary')}</title></head>
<body style="font-family:Inter,Segoe UI,sans-serif;background:#f5f7fa;margin:0;padding:24px;">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #e0e4ea;">
    <div style="background:#00bfb3;color:#fff;padding:20px 24px;">
      <div style="font-size:12px;opacity:0.9;letter-spacing:0.06em;text-transform:uppercase;">Elastic Observability · Incident Summary</div>
      <h1 style="margin:8px 0 0;font-size:20px;font-weight:600;">{report.get('title', 'Checkout degradation')}</h1>
    </div>
    <div style="padding:24px;">
      <table style="width:100%;margin-bottom:20px;font-size:14px;">
        <tr><td style="color:#666;padding:4px 0;">Incident ID</td><td><code>{report.get('incident_id', '—')}</code></td></tr>
        <tr><td style="color:#666;padding:4px 0;">Service</td><td><strong>{report.get('service', '—')}</strong></td></tr>
        <tr><td style="color:#666;padding:4px 0;">Blast tenant</td><td>{report.get('tenant', '—')}</td></tr>
        <tr><td style="color:#666;padding:4px 0;">Severity</td><td>{report.get('severity', 'high')}</td></tr>
        <tr><td style="color:#666;padding:4px 0;">Status</td><td>{report.get('status', 'resolved')}</td></tr>
        <tr><td style="color:#666;padding:4px 0;">Approval</td><td>{approval_line}</td></tr>
      </table>
      <h2 style="font-size:15px;margin:0 0 8px;">Root cause</h2>
      <p style="font-size:14px;line-height:1.55;color:#333;margin:0 0 20px;">{report.get('root_cause', '')}</p>
      <h2 style="font-size:15px;margin:0 0 8px;">Impact</h2>
      <p style="font-size:14px;line-height:1.55;color:#333;margin:0 0 20px;">{report.get('impact', '')}</p>
      <h2 style="font-size:15px;margin:0 0 8px;">Evidence</h2>
      <ul style="font-size:14px;color:#333;padding-left:20px;margin:0 0 20px;">{ev_items}</ul>
      <h2 style="font-size:15px;margin:0 0 8px;">Timeline</h2>
      <table style="width:100%;font-size:13px;border-collapse:collapse;margin-bottom:20px;">{tl_rows}</table>
      <h2 style="font-size:15px;margin:0 0 8px;">Remediation</h2>
      <ul style="font-size:14px;color:#333;padding-left:20px;margin:0;">{rem_items}</ul>
    </div>
    <div style="padding:16px 24px;background:#f8f9fb;font-size:12px;color:#888;border-top:1px solid #e0e4ea;">
      Generated by Elastic Co. RCA agent · {report.get('generated_at', '')}
    </div>
  </div>
</body></html>"""


def send_incident_email(report: dict, to: str) -> tuple[bool, str]:
    """Try Kibana email connector, then SMTP, then write HTML file."""
    subject = report.get("email_subject") or f"[Elastic Co.] Incident resolved — {report.get('service', 'service')}"
    html = render_email_html(report)
    text = report.get("summary", "")

    connector_id = os.environ.get("KIBANA_EMAIL_CONNECTOR_ID")
    if connector_id:
        ok, msg = _send_via_kibana_connector(connector_id, to, subject, html, text)
        if ok:
            return True, msg

    if os.environ.get("SMTP_HOST"):
        ok, msg = _send_via_smtp(to, subject, html, text)
        if ok:
            return True, msg

    out_dir = ROOT / "output" / "incident-emails"
    out_dir.mkdir(parents=True, exist_ok=True)
    safe_id = report.get("incident_id", "incident").replace("/", "-")
    path = out_dir / f"{safe_id}.html"
    path.write_text(html, encoding="utf-8")
    template = KIBANA_DIR / "incident-email-template.txt"
    if not template.exists():
        template.write_text(
            "Subject: {subject}\nTo: {to}\n\n{summary}\n\n(HTML body saved separately)\n",
            encoding="utf-8",
        )
    return False, f"Email connector/SMTP not configured — saved to {path}"


def _send_via_kibana_connector(
    connector_id: str, to: str, subject: str, html: str, text: str
) -> tuple[bool, str]:
    body = {
        "params": {
            "to": [to],
            "subject": subject,
            "message": text or html,
            "messageType": "html" if html else "plain",
        }
    }
    if html:
        body["params"]["message"] = html
    r = requests.post(
        f"{KIBANA_URL}/api/actions/connector/{connector_id}/_execute",
        headers=KBN_HEADERS,
        json=body,
        timeout=60,
    )
    if r.status_code < 300:
        return True, f"Sent via Kibana connector {connector_id}"
    return False, f"Connector failed: {r.status_code} {r.text[:200]}"


def _send_via_smtp(to: str, subject: str, html: str, text: str) -> tuple[bool, str]:
    host = os.environ["SMTP_HOST"]
    port = int(os.environ.get("SMTP_PORT", "587"))
    user = os.environ.get("SMTP_USER")
    password = os.environ.get("SMTP_PASSWORD")
    from_addr = os.environ.get("SMTP_FROM", user or "elasticco-rca@elastic.co")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to
    if text:
        msg.attach(MIMEText(text, "plain"))
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(host, port, timeout=30) as smtp:
        smtp.starttls()
        if user and password:
            smtp.login(user, password)
        smtp.sendmail(from_addr, [to], msg.as_string())
    return True, f"Sent via SMTP {host}"
